{% set version = "0.16.6" %}

package:
  name: ycm-cmake-modules
  version: {{ version }}

source:
  url: https://github.com/robotology/ycm/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 632fdc3d05770ed09195b8730ca60ac07cce08b187c3b66585de0a9d71ef5a7c

build:
  number: 0

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - ninja

test:
  commands:
    - test -f ${PREFIX}/share/cmake/YCM/YCMConfig.cmake  # [not win]
    - if not exist %PREFIX%\\Library\\share\\cmake\\YCM\\YCMConfig.cmake exit 1  # [win]

about:
  home: https://github.com/robotology/ycm
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Extra CMake Modules for YARP and friends.

extra:
  recipe-maintainers:
    - traversaro
