{% set version = "0.16.4" %}

package:
  name: ycm-cmake-modules
  version: {{ version }}

source:
  url: https://github.com/robotology/ycm/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a20b89aa5b04a9ad685a9641dd99351b62b9072a769ded50c8ddd7893ff150a1

build:
  number: 0

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - ninja

test:
  commands:
    - test -f ${PREFIX}/share/cmake/YCM/YCMConfig.cmake  # [not win]
    - if not exist %PREFIX%\\Library\\share\\cmake\\YCM\\YCMConfig.cmake exit 1  # [win]

about:
  home: https://github.com/robotology/ycm
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Extra CMake Modules for YARP and friends.

extra:
  recipe-maintainers:
    - traversaro
